# --- File: docker-compose.yml (Definitive Final Version - Synchronized) ---
# Removed 'version: 3.8' as it is obsolete and causes a warning.

services:
  postgres:
    image: postgres:13
    container_name: hres_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - hres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    container_name: hres_mlflow
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
      - ./docker/mlflow_startup.sh:/mlflow_app/mlflow_startup.sh  # Mount the script
    networks:
      - hres_network
    depends_on:
      - postgres
        condition: service_healthy
    command: ["bash", "/mlflow_app/mlflow_startup.sh"]  # Execute the script

  airflow-init:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    container_name: hres_airflow_init
    env_file: .env
    networks:
      - hres_network
    depends_on:
      - postgres
        condition: service_healthy
    command: ["bash", "-c", "airflow db migrate && airflow users create --username ${AIRFLOW_WWW_USER_USERNAME} --password ${AIRFLOW_WWW_USER_PASSWORD} --firstname Airflow --lastname User --role Admin --email airflow@example.com || true"]
    restart: "no"

  airflow-webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    container_name: hres_airflow_webserver
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../requirements.txt:/opt/airflow/requirements.txt
    networks:
      - hres_network
    depends_on:
      - airflow-init
        condition: service_completed_successfully
      - mlflow
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: ["airflow", "webserver"]
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    container_name: hres_airflow_scheduler
    env_file: .env
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../requirements.txt:/opt/airflow/requirements.txt
    networks:
      - hres_network
    depends_on:
      - airflow-webserver
        condition: service_healthy
    command: ["airflow", "scheduler"]
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: hres_api
    env_file: .env
    volumes:
      - ../src:/app/src
      - ../api:/app/api
    ports:
      - "8081:8080"
    networks:
      - hres_network
    depends_on:
      - mlflow
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    container_name: hres_ui
    volumes:
      - ../ui.py:/app/ui.py
      - ../logo.png:/app/logo.png
    ports:
      - "8501:8501"
    networks:
      - hres_network
    depends_on:
      - api
        condition: service_healthy
    restart: unless-stopped

  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter
    container_name: hres_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../src:/home/jovyan/src
      - ../notebooks:/home/jovyan/notebooks
      - ../requirements.txt:/home/jovyan/requirements.txt
    networks:
      - hres_network
    restart: unless-stopped

networks:
  hres_network:
    driver: bridge

volumes:
  postgres_db_data:
  mlflow_artifacts: